### ISSUE TITLE
Does anyone have a working requirements.txt?

### ISSUE THREAD

**Issue by Chad-Wyck** [NousResearch/Hermes-Function-Calling#10]
I've been through every issue posts so far and then some, native, conda, WSL all turn into a dependency nightmare that it makes way more sense to just ask for a working requirements.txt and what OS / environment your on. 

Ty in advance!

**Comment by OB-SPrince** [comment]
The current requirements.txt is very straightforwards for any MacOS or Linux OS that supports python3.
Many users have their choice or preference on how you make your virtual environment in python, I prefer [pyenv](https://github.com/pyenv/pyenv), but I think where you may be stumbling is on the torch requirements, which needs you to have a working "wheels" package installed. Also pyenv does not work in windows or WSL2. I decided to quit gaming and focus on AI, so I don't run windows anymore for this reason.

This probably confuses alot of people coming from windows systems, as the CUDA implementation in WSL2 is not implemented completely there yet. You cannot do CUDA in docker with windows, either. If you don't use windows or WSL2, then you may need to see if your OS has a python3 wheels version for the system python, installing this (even though you wont use that version of it) will get the system to install any dependencies that wheels needs to compile.

That being said, there are no issues running `pip install --upgrade requirements.txt` on any system that supports Torch 2.2, latest transformers and protobuf. The rest of the requirements are very platform agnostic.
