### ISSUE TITLE
pydantic_schema seems not passed to LLM in the first iteration

### ISSUE THREAD

**Issue by Tuanshu** [NousResearch/Hermes-Function-Calling#11]
in `jsonmode.py`, 

`pydantic_schema = Character.schema_json()`
...
```
def generate_json_completion(self, query, chat_template, max_depth=5):
        try:
            depth = 0
            sys_prompt = "You are a helpful assistant that answers in JSON. Here's the json schema you must adhere to:\n<schema>\n{schema}\n<schema>"
```
if my understanding is correct, seem the pydantic_schema is not passed to `{schema}` here, is this supposed behavior?

**Comment by interstellarninja** [comment]
hi Tuanshu, thanks for pointing it out. It was a typo and now it's been fixed. 

we fine-tuned the model with pydantic schema as part of the system prompt so it'd be better to pas it in the system prompt.
