### ISSUE TITLE
Requirements issue with torch==2.1.2

### ISSUE THREAD

**Issue by lightningRalf** [NousResearch/Hermes-Function-Calling#16]
Hello, just wanted to try this out, but I receive the following issue:

ERROR: Could not find a version that satisfies the requirement torch==2.1.2 (from versions: 2.2.0, 2.2.1, 2.2.2)
ERROR: No matching distribution found for torch==2.1.2

Steps I performed before:
git clone https://github.com/NousResearch/Hermes-Function-Callin
python -m venv .venv
pip install -r requirements.txt

**Comment by suparious** [comment]
Yeah, if you are not on an Nvidia CUDA system with python 3.11, then you may need to build your own torch. This 2.1.2 requirement is related Flash_Attn.

It is likely you are trying this on a MacBook or in Windows, I would guess.
