### ISSUE TITLE
json mode schema tag not closed

### ISSUE THREAD

**Issue by Benjoyo** [NousResearch/Hermes-Function-Calling#19]
https://github.com/NousResearch/Hermes-Function-Calling/blob/8b8c00ca95a12d3ac68200625a08152481b49004/jsonmode.py#L94

Minor thing, but could confuse the model slightly I guess.

**Comment by teknium1** [comment]
fixed https://github.com/NousResearch/Hermes-Function-Calling/commit/d3e8b88e61533c43b286b189a5521509e555dbbc
