### ISSUE TITLE
Issue with calling Functions with multiple arguments

### ISSUE THREAD

**Issue by GeethaCharan31** [NousResearch/Hermes-Function-Calling#27]
I have a custom function to fetch the data between two dates in a dataframe. It raises the following error 
**INFO     [functioncall.py:160] Could not execute function: 'str' object has no attribute 'handlers'**

also I had error stating the maximum arguments I can have is only 2. Is there is workaround to have more than 2 arguments. 

The custom function is as follows:
![image](https://github.com/NousResearch/Hermes-Function-Calling/assets/56082784/3699ddc5-6faf-4041-ad43-a71367b50cfc)

**Comment by SwamiKannan** [comment]
This is a problem with using langchain tool object. I basically got the StructuredTool object (which is created for every function) based on the function name that the LLM returned, extracted the function object from it and ran it manually as func(*args)
